name: Deploy Panels to Vercel
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - panel: admin_panel
          - panel: merchant_panel
          - panel: emlakci_panel
          - panel: arac_satis_panel
          - panel: rent_a_car_panel
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Build ${{ matrix.panel }}
        run: |
          cd ${{ matrix.panel }}
          flutter pub get
          flutter build web --release

      - name: Set project ID
        run: |
          case "${{ matrix.panel }}" in
            admin_panel) echo "PROJ_ID=${{ secrets.VERCEL_ADMIN_PROJECT_ID }}" >> $GITHUB_ENV ;;
            merchant_panel) echo "PROJ_ID=${{ secrets.VERCEL_MERCHANT_PROJECT_ID }}" >> $GITHUB_ENV ;;
            emlakci_panel) echo "PROJ_ID=${{ secrets.VERCEL_EMLAKCI_PROJECT_ID }}" >> $GITHUB_ENV ;;
            arac_satis_panel) echo "PROJ_ID=${{ secrets.VERCEL_ARAC_SATIS_PROJECT_ID }}" >> $GITHUB_ENV ;;
            rent_a_car_panel) echo "PROJ_ID=${{ secrets.VERCEL_RENT_A_CAR_PROJECT_ID }}" >> $GITHUB_ENV ;;
          esac

      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          cd ${{ matrix.panel }}/build/web
          vercel deploy --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ env.PROJ_ID }}
